### ISSUE TITLE
TypeError: OsuStrategy is not a constructor

### ISSUE THREAD

**Issue by OrlowskiAdam** [MiraiSubject/passport-osu#1]
Hello,
I tried to set up OAuth for osu! using your package passport-osu. Unfortunately when I'm starting my application, the error pops up:
`TypeError: OsuStrategy is not a constructor`

Repository to recreate the problem: https://github.com/OrlowskiAdam/erw

Set credentials in `src/server/config/keys.js`. Data for MongoDB is not necessary
Run application using `npm run dev`
> Now the problem should appear

**Comment by MiraiSubject** [comment]
If you're using passport-osu in Javascript you should use `new OsuStrategy.default`. I will update the documentation accordingly for that.

I tested that with the code you sent. 

This is currently a side effect of how `export default` works in TS making it `exports.default` in JS. (That's why .default is needed)

The `module.exports` way is only possible if one module gets exported so the interfaces and types that I set for the TS counterpart of this wouldn't work anymore. 

So to keep the balance with the two I'll keep it like this and update the documentation for it. 

P.S. Please use the latest LTS of node.js 😉
